# Generated by Django 3.1.5 on 2021-01-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculate',
            name='sum',
        ),
    ]
